### ISSUE TITLE
Update process

### ISSUE THREAD

**Issue by fuatakgun** [openlumi/owrt-installer#5]
First of all, thank you for this great tool, i have been actively using it for the last 6 months.

So, i am looking for a way to update my openwrt version but not sure which method to follow. Can you update instructions to include update process?

Thanks

**Comment by devbis** [comment]
If you're using version 19.07 and higher you should use the generic OpenWrt upgrade procedure. (https://openwrt.org/docs/guide-quick-start/sysupgrade.luci)
Use `sysupgrade` images from https://github.com/openlumi/openwrt/releases

DTB upgrade may be required for new LED driver support, you can install it after the upgrade. 
Download *.dtb file to the gateway and 

```
flash_erase /dev/mtd2 0 0
nandwrite -p /dev/mtd2 -p openwrt-imx6-imx6ull-xiaomi-lumi.dtb
```

**Comment by fuatakgun** [comment]
Thanks it is clear, resolving it
